name: legalsum
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.11.0
  - aiohttp=3.7.3
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.2.2
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - catalogue=1.0.0
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.1.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - geckodriver=0.27.0
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.34.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ipykernel=5.1.0
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.18.0
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libuv=1.40.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.1
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - more-itertools=8.5.0
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - murmurhash=1.0.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - ninja=1.10.1
  - notebook=6.2.0
  - numpy=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11.3.2
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - plac=0.9.6
  - pluggy=0.13.1
  - preshed=3.0.2
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.13
  - prompt_toolkit=3.0.13
  - protobuf=3.14.0
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.4
  - pyjwt=2.0.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.1.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.0
  - pytz=2020.1
  - pywin32=300
  - pywinpty=0.5.7
  - pyzmq=21.0.1
  - qt=5.9.7
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rope=0.18.0
  - rsa=4.7
  - scikit-learn=0.23.2
  - seaborn=0.11.0
  - selenium=3.141.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - sip=4.19.24
  - six=1.15.0
  - soupsieve=2.0.1
  - spacy=2.3.2
  - sqlite=3.33.0
  - srsly=1.0.2
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.2
  - testpath=0.4.4
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wasabi=0.8.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - cython==0.29.14
    - dataclasses==0.6
    - future==0.18.2
    - gensim==3.8.3
    - rouge==1.0.0
    - scipy==1.5.3
    - smart-open==3.0.0
    - torchtest==0.5
